import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:hb_social/core/theme/app_theme.dart';
import 'package:hb_social/core/widgets/coming_soon_sheet.dart';
import 'package:hb_social/core/widgets/hb_button.dart';
import 'package:hb_social/core/widgets/hb_filter_chips_row.dart';
import 'package:hb_social/core/widgets/hb_input.dart';
import 'package:hb_social/features/admin/presentation/widgets/admin_detail_panel.dart';
import 'package:hb_social/features/admin/presentation/widgets/admin_list_page.dart';

class AdminCalendarsPage extends StatefulWidget { const AdminCalendarsPage({super.key}); @override State<AdminCalendarsPage> createState() => _AdminCalendarsPageState(); }
class _AdminCalendarsPageState extends State<AdminCalendarsPage> { int status = 0;
  void _future() => showComingSoonInfo(context, icon: Icons.schedule_outlined, title: 'common.coming_soon_title'.tr(), message: 'admin.common.arrivesWith'.tr(namedArgs: {'phase': 'P44'}));
  @override Widget build(BuildContext context) { final panel = GoRouterState.of(context).uri.queryParameters['panel'] == 'calendar'; return Stack(children: [AdminListPage(title: 'admin.calendars.title'.tr(), description: 'admin.calendars.description'.tr(), actions: [HBButton.secondary(label: 'admin.calendars.importCsv'.tr(), onPressed: _future), HBButton.primary(label: 'admin.calendars.newCalendar'.tr(), onPressed: _future)], filters: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [const Wrap(spacing: AppSpacing.sm, children: [AdminCompactDropdown(label: '—', items: []), AdminCompactDropdown(label: '—', items: [])]), const SizedBox(height: AppSpacing.sm), HBFilterChipsRow(labels: [for (final key in ['all', 'active', 'expiring', 'expired', 'draft']) 'admin.calendars.status.$key'.tr()], selectedIndex: status, onChanged: (value) => setState(() => status = value)), const SizedBox(height: AppSpacing.sm), HBInput(hint: 'admin.calendars.searchSpecies'.tr(), prefixIcon: const Icon(Icons.search, size: 18))]), kpis: [for (final key in ['active', 'expiring30d', 'regionsCovered', 'speciesCovered']) AdminKpiValue(label: 'admin.calendars.kpi.$key'.tr(), value: '—')], headers: [for (final key in ['country', 'region', 'species', 'opening', 'closing', 'schedule', 'source', 'validity', 'actions']) 'admin.calendars.table.$key'.tr()], emptyMessage: 'admin.calendars.empty'.tr(), content: Column(children: [Container(padding: const EdgeInsets.all(AppSpacing.sm), decoration: BoxDecoration(color: LightModeColors.lightPrimarySoft, borderRadius: BorderRadius.circular(AppRadius.sm)), child: Text('admin.calendars.notice'.tr(), style: context.textStyles.bodySmall?.withColor(LightModeColors.lightForest))), const SizedBox(height: AppSpacing.lg), Text('admin.calendars.empty'.tr(), style: context.textStyles.titleMedium), const SizedBox(height: AppSpacing.xs), Text('admin.calendars.emptyMessage'.tr(), textAlign: TextAlign.center, style: context.textStyles.bodySmall)])), if (panel) AdminDetailOverlay(onClose: _close, panel: AdminCalendarDetailPanel(onClose: _close, onFuture: _future))]); }
  void _close() => context.go('/admin/calendars?debugPreview=true'); }
class AdminCalendarDetailPanel extends StatelessWidget { final VoidCallback onClose; final VoidCallback onFuture; const AdminCalendarDetailPanel({super.key, required this.onClose, required this.onFuture});
  @override Widget build(BuildContext context) => AdminDetailPanel(title: 'admin.calendars.detailTitle'.tr(), onClose: onClose, actions: [HBButton.secondary(label: 'admin.calendars.saveDraft'.tr(), onPressed: onFuture), HBButton.primary(label: 'admin.calendars.publish'.tr(), onPressed: onFuture)], body: Column(children: [for (final key in ['country', 'region', 'unit', 'species', 'period', 'days', 'hours', 'notes', 'source', 'validity']) Padding(padding: const EdgeInsets.only(bottom: AppSpacing.sm), child: HBInput(label: 'admin.calendars.fields.$key'.tr(), hint: '—', enabled: false))])); }