import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:hb_social/core/theme/app_theme.dart';
import 'package:hb_social/core/widgets/coming_soon_sheet.dart';
import 'package:hb_social/core/widgets/hb_button.dart';
import 'package:hb_social/core/widgets/hb_card.dart';
import 'package:hb_social/core/widgets/hb_empty_state.dart';
import 'package:hb_social/features/admin/domain/admin_module.dart';
import 'package:hb_social/features/admin/domain/admin_role.dart';
import 'package:hb_social/features/admin/presentation/widgets/admin_list_page.dart';

class AdminRolesPage extends StatelessWidget { const AdminRolesPage({super.key});
  void _future(BuildContext context) => showComingSoonInfo(context, icon: Icons.schedule_outlined, title: 'common.coming_soon_title'.tr(), message: 'admin.common.arrivesWith'.tr(namedArgs: {'phase': 'P40'}));
  @override Widget build(BuildContext context) => CustomScrollView(slivers: [SliverToBoxAdapter(child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [AdminListHeader(title: 'admin.rolesPage.title'.tr(), description: 'admin.rolesPage.description'.tr(), actions: [HBButton.primary(label: 'admin.rolesPage.invite'.tr(), onPressed: () => _future(context))]), const SizedBox(height: AppSpacing.md), LayoutBuilder(builder: (context, constraints) { final wide = constraints.maxWidth >= 1100; final staff = _StaffCard(onFuture: () => _future(context)); final matrix = const _PermissionMatrix(); return wide ? Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Expanded(child: staff), const SizedBox(width: AppSpacing.md), Expanded(flex: 2, child: matrix)]) : Column(children: [staff, const SizedBox(height: AppSpacing.md), matrix]); }), const SizedBox(height: AppSpacing.lg)]))]); }
class _StaffCard extends StatelessWidget { final VoidCallback onFuture; const _StaffCard({required this.onFuture});
  @override Widget build(BuildContext context) => HBCard(radius: AppRadius.sm, padding: const EdgeInsets.all(AppSpacing.md), child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Text('admin.rolesPage.staff'.tr(), style: context.textStyles.titleMedium?.bold), const SizedBox(height: AppSpacing.md), HBEmptyState(icon: Icons.people_outline, title: 'admin.rolesPage.staffEmpty'.tr(), message: 'admin.rolesPage.staffEmptyMessage'.tr(), padding: const EdgeInsets.symmetric(vertical: AppSpacing.xl))])); }
class _PermissionMatrix extends StatelessWidget { const _PermissionMatrix();
  bool _allowed(AdminRole role, String slug) => switch (role) { AdminRole.superadmin => true, AdminRole.admin => slug != 'payments' && slug != 'security', AdminRole.moderator => ['content', 'communities', 'reports', 'rules', 'support'].contains(slug), AdminRole.adsReviewer => ['ad-review', 'advertisers'].contains(slug), AdminRole.finance => ['listings', 'orders', 'revenue'].contains(slug), AdminRole.huntingDataEditor => ['calendars', 'maps'].contains(slug) };
  @override Widget build(BuildContext context) { final modules = [for (final section in adminModuleSections) ...section.modules]; return Material(color: Colors.white, borderRadius: BorderRadius.circular(AppRadius.sm), child: Padding(padding: const EdgeInsets.all(AppSpacing.md), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('admin.rolesPage.matrix'.tr(), style: context.textStyles.titleMedium?.bold), const SizedBox(height: AppSpacing.xs), Text('admin.rolesPage.matrixNote'.tr(), style: context.textStyles.bodySmall?.withColor(LightModeColors.lightTextTertiary)), const SizedBox(height: AppSpacing.md), SingleChildScrollView(scrollDirection: Axis.horizontal, child: Table(defaultColumnWidth: const IntrinsicColumnWidth(), children: [TableRow(children: [const SizedBox(width: 150), for (final role in AdminRole.values) Padding(padding: const EdgeInsets.all(AppSpacing.xs), child: Text(role.labelKey.tr(), textAlign: TextAlign.center, style: context.textStyles.labelSmall))]), for (final module in modules) TableRow(children: [Padding(padding: const EdgeInsets.symmetric(vertical: AppSpacing.xs), child: Text(module.titleKey.tr(), style: context.textStyles.bodySmall)), for (final role in AdminRole.values) Icon(_allowed(role, module.slug) ? Icons.check : Icons.remove, size: 18, color: _allowed(role, module.slug) ? LightModeColors.lightSuccess : LightModeColors.lightTextTertiary)])])), const SizedBox(height: AppSpacing.md), Text('admin.rolesPage.mfa'.tr(), style: context.textStyles.bodySmall?.withColor(LightModeColors.lightTextTertiary))]))); }
}